version: '2'
services:
    redis:
        image: redis:1.0.0
        build:
            context: ./
            dockerfile: ./Dockerfile
        container_name: redis
        restart: always
        tty: true
        ports:
            - "6379:6379/udp"
        logging:
            driver: json-file
            options:
                max-size: 5m
#         volumes:
#             - /etc/localtime:/etc/localtime
#             - /etc/timezone:/etc/timezone
