version: '2'
services:
    mysql:
        image: mysql:2.0.0
        build:
            context: ./
            dockerfile: ./Dockerfile
        container_name: mysql
        restart: always
        tty: true
        ports:
            - "3306:3306/tcp"
        logging:
            driver: json-file
            options:
                max-size: 5m
#         volumes:
#             - /etc/localtime:/etc/localtime
#             - /etc/timezone:/etc/timezone
