version: '2'
services:
    omnidb:
        image: omnidb:1.0.0
        build:
            context: ./
            dockerfile: ./Dockerfile
        container_name: omnidb
        restart: always
        tty: true
        ports:
            - "8000:8000/tcp"
            - "25482:25482/tcp"
        logging:
            driver: json-file
            options:
                max-size: 5m
#         volumes:
#             - /etc/localtime:/etc/localtime
#             - /etc/timezone:/etc/timezone
