http:
    addr: :8080

database:
    username: root
    password: 123456
    host: localhost
    port: 3306
    dbname: playground
    logmode: true

redis:
    host: localhost
    port: 6379
    password: 123456