global:
  scrape_interval:     60s
  scrape_timeout:      60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: playground
    static_configs:
      - targets: ["playground:8080"]
        labels:
          instance: playground
